// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRiVZid4xjp1qnsbjCpW2-P2_E8Ou_fWU',
    appId: '1:159233035566:web:899ff2d225d24ee4497ebf',
    messagingSenderId: '159233035566',
    projectId: 'charla24-7',
    authDomain: 'charla24-7.firebaseapp.com',
    storageBucket: 'charla24-7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvFZtzZPDWXZfzK1LXYsaa5KurdiaS00Y',
    appId: '1:159233035566:android:6c9b097a0ded072d497ebf',
    messagingSenderId: '159233035566',
    projectId: 'charla24-7',
    storageBucket: 'charla24-7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzsUL7ETlppPenFmg3XRJkfvcL2gsNegM',
    appId: '1:159233035566:ios:d5a0f9919bb9ddf8497ebf',
    messagingSenderId: '159233035566',
    projectId: 'charla24-7',
    storageBucket: 'charla24-7.appspot.com',
    iosClientId: '159233035566-cckrk9n11s860499oifif8a14bh4cagi.apps.googleusercontent.com',
    iosBundleId: 'com.example.charla',
  );
}
